console.log("main.js obecny");

(function ($) {

    //Notification handler
    abp.event.on('abp.notifications.received', function (userNotification) {
        abp.notifications.showUiNotifyForUserNotification(userNotification);

        //Desktop notification
        Push.create("AbpZeroTemplate", {
            body: userNotification.notification.data.message,
            icon: abp.appPath + 'images/app-logo-small.png',
            timeout: 6000,
            onClick: function () {
                window.focus();
                this.close();
            }
        });
    });

    //serializeFormToObject plugin for jQuery
    $.fn.serializeFormToObject = function () {
        var $form = $(this);
        var fields = $form.find('[disabled]');
        fields.prop('disabled', false);
        var json = $form.serializeJSON();
        fields.prop('disabled', true);
        return json;
    };

    //Configure blockUI
    if ($.blockUI) {
        $.blockUI.defaults.baseZ = 2000;
    }
})(jQuery);

const LogRedError = (err) =>
{
    if (err.stack?.length)
        console.log("%c" + err.stack, "background: red;");
    else if (err.responseJSON?.error) // jak nie ma klamer to Minifier.cs się wywala
    {
        console.log("%c" + err.responseJSON.error.message, "background: red;");
    }
    else
        console.log("%c" + err, "background: red;");
}

const CreateError = () => {
    throw new Error("Boooom!");
};

// =============================== Somee.com ===========================================================================
// Rozwiązanie problemu z dodawaniem reklam przez Somee.com. Wykryte przez testy Selenium IDE
// Jeśli szybko dokonuje się akcji kreacji lub edycji w panelu konfiguracyjnym raz po raz to z niewiadomych przyczyn serwer Somee.com czasami dodaje do response swoje reklamy. Nawet jeśli odpowiedź nie jest typu html.
// W abp.jquery.js return $.Deferred(function ($dfd), jest wersja kodu, która analizuje czy reklamy zostały dodane. Poniżej reszta kodu do analizy dodawanych reklam.
// =====================================================================================================================

// $(document).on("ajaxStop", () => setTimeout(() => RemoveSomeeComAdds(), 50));

// const GetCurrDateTime = () =>
// {
//     const currentDate = new Date();
//     return currentDate.getDate() + "/"
//         + (currentDate.getMonth() + 1) + "/"
//         + currentDate.getFullYear() + " "
//         + currentDate.getHours() + ":"
//         + currentDate.getMinutes() + ":"
//         + currentDate.getSeconds();
// };

// const RemoveSomeeComAdds = () =>
// {
//     try
//     {
//         $("center").remove();
//         $("script:lang(JavaScript)").remove();
//         $("script[src = 'http://ads.mgmt.somee.com/serveimages/ad2/WholeInsert5.js']").remove();
//         $("a[href = 'http://somee.com']").parent().parent().parent().remove();
//         $("div[style = 'opacity: 0.9; z-index: 2147483647; position: fixed; left: 0px; bottom: 0px; height: 65px; right: 0px; display: block; width: 100%; background-color: #202020; margin: 0px; padding: 0px;']").remove();
//     }
//     catch (ex)
//     {
//         LogRedError(ex);
//         abp.message.error("Coś poszło nie tak :<");
//     }
// };

// window.onload = () =>
// {
//     RemoveSomeeComAdds();
// }

// const SomeeComAdds = "<\\!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->\\n<center><a href=\"http://somee.com\">Web hosting by Somee.com</a></center>\\n</textarea></xml><\\/script></noframes></noscript></object></layer></style></title></applet>\\n<\\script lang=\"JavaScript\">aScr = document.createElement('script');aScr.src = location.protocol + \"//ads.mgmt.somee.com/serveimages/ad2/WholeInsert5.js\";document.body.appendChild(aScr);<\\/script>\\n<\\!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->";
 
// const CheckSomeeComAddsError = (jqXHR) =>
// {
//     let ret = null;
//     try
//     {
//         if (jqXHR.status === 200 && jqXHR.readyState === 4 && jqXHR.statusText === "OK" && jqXHR.responseText.includes("SCRIPT GENERATED BY SERVER! PLEASE REMOVE"))
//         {
//             ret = $.parseJSON(CleanResponseFromSomeeComAdds(jqXHR.responseText));
//             // SetSomeeComAddsErrorToLocalStorage(jqXHR);
//         }
//         // else
//         // {
//         //     console.log("error - ", jqXHR);
//         //     abp.message.error("Coś poszło nie tak :(");
//         // }
//     }
//     catch (ex)
//     {
//         LogRedError(ex);
//         abp.message.error("Coś poszło nie tak :<");
//     }
//
//     return ret;
// };

// const CleanResponseFromSomeeComAdds = (responseText) =>
// {
//     const adds = responseText.substr(responseText.indexOf('<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->'),
//         responseText.lastIndexOf('<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->'));
//     return responseText.replaceAll(adds, "");
// };

// const SetSomeeComAddsErrorToLocalStorage = (jqXHR) =>
// {
//     try
//     {
//         jqXHR.actionTime = GetCurrDateTime();
//         if (localStorage.getItem("somee_com_adds_error") === null)
//         {
//             localStorage.setItem("somee_com_adds_error", JSON.stringify([jqXHR]));
//         }
//         else
//         {
//             const previousErrors = $.parseJSON(localStorage.getItem("somee_com_adds_error"));
//             previousErrors.push(jqXHR);
//             localStorage.setItem("somee_com_adds_error", JSON.stringify(previousErrors));
//         }
//
//         console.log("Wyczyszczone błędy reklam somee.com", $.parseJSON(localStorage.getItem("somee_com_adds_error")));
//     }
//     catch (ex)
//     {
//         LogRedError(ex);
//         abp.message.error("Coś poszło nie tak :<");
//     }
// };
